import { CreditCard } from "./types";

export const creditCardData: CreditCard[] = [
  {
    bank: "HDFC Bank",
    card_name: "HDFC Regalia",
    url: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card",
    annual_percentage_rate: "40.8%",
    joining_fee: "₹2,500",
    annual_fee: "₹2,500",
    benefits: [
      "Complimentary airport lounge access",
      "Reward points on spends",
      "Dining benefits",
    ],
    summary:
      "The HDFC Regalia Credit Card is a popular mid-premium credit card designed for frequent travelers and lifestyle enthusiasts. It offers complimentary access to domestic and international airport lounges through Priority Pass, along with a rewarding points program on everyday and high-value spends. Cardholders also enjoy exclusive dining discounts at select restaurants and periodic promotions. While it comes with a joining and annual fee of ₹2,500, the value it delivers through travel and lifestyle perks can easily outweigh the cost for those who use it actively. However, its high annual percentage rate makes it less suitable for users who carry outstanding balances.",
    advantages: [
      "Complimentary airport lounge access at domestic and international airports.",
      "Reward points on regular and high-value transactions.",
      "Exclusive dining privileges with discounts at partner restaurants.",
      "Travel insurance coverage and fuel surcharge waivers.",
      "Potential annual fee waiver on achieving high annual spends.",
    ],
    disadvantages: [
      "High annual percentage rate (APR) of 40.8%, making it expensive for carrying balances.",
      "Moderate annual fee of ₹2,500, which may not suit low-spending users.",
      "Limited benefits outside of travel and dining categories.",
      "Better premium cards are available in the market with superior benefits in certain categories.",
    ],
    ratings: {
      lounge_access: 8.5,
      reward_points_program: 7.5,
      dining_benefits: 7,
      annual_fee_value: 7,
      apr_interest_rate: 4,
      overall_versatility: 7.5,
    },
  },
  {
    bank: "SBI",
    card_name: "SBI SimplySAVE",
    url: "https://www.sbicard.com/en/personal/credit-cards/shopping/simplysave-sbi-card.page",
    annual_percentage_rate: "42.0%",
    joining_fee: "₹499",
    annual_fee: "₹499",
    benefits: [
      "10x reward points on dining, movies, groceries, and departmental stores",
    ],
    summary:
      "The SBI SimplySAVE Credit Card is an entry-level card tailored for individuals who frequently spend on everyday categories such as dining, groceries, movies, and departmental stores. With a modest joining and annual fee of ₹499, the card offers 10X reward points on select categories, enhancing savings on routine expenses. New cardholders benefit from a welcome offer of 2,000 bonus reward points upon spending ₹2,000 within the first 60 days. Additionally, the card provides a 1% fuel surcharge waiver on transactions between ₹500 and ₹3,000, capped at ₹100 per statement cycle. An annual fee waiver is available upon reaching annual spends of ₹1,00,000. While the card excels in rewarding everyday purchases, it lacks premium features such as lounge access or comprehensive travel benefits, making it best suited for budget-conscious users seeking to maximize rewards on daily expenditures.",
    advantages: [
      "10X reward points on dining, movies, groceries, and departmental store spends.",
      "Low joining and annual fee of ₹499.",
      "Welcome bonus of 2,000 reward points on spending ₹2,000 within the first 60 days.",
      "1% fuel surcharge waiver on transactions between ₹500 and ₹3,000, up to ₹100 per statement cycle.",
      "Annual fee waiver on spending ₹1,00,000 or more in the previous year.",
      "Contactless payment feature for quick and secure transactions.",
      "Global acceptance at over 24 million outlets worldwide.",
    ],
    disadvantages: [
      "High annual percentage rate (APR) of 42.0%, making it costly for revolving credit.",
      "Limited reward redemption options, primarily through select brand vouchers or statement credit.",
      "No access to airport lounges or premium travel benefits.",
      "Reward points have a low monetary value (4 points = ₹1).",
      "Lacks additional perks such as insurance coverage or concierge services.",
    ],
    ratings: {
      reward_points_program: 7.5,
      annual_fee_value: 8.0,
      fuel_surcharge_waiver: 7.0,
      welcome_benefits: 7.5,
      apr_interest_rate: 4.0,
      overall_versatility: 6.5,
    },
  },
  {
    bank: "ICICI Bank",
    card_name: "ICICI Coral",
    url: "https://www.icicibank.com/personal-banking/cards/credit-card/coral-card",
    annual_percentage_rate: "40.8%",
    joining_fee: "₹500",
    annual_fee: "₹500",
    benefits: [
      "2x rewards on online spends",
      "Complimentary movie tickets",
      "Dining discounts",
    ],
    summary:
      "The ICICI Bank Coral Credit Card is an entry-level lifestyle card designed for individuals seeking rewards on everyday spending. With a modest joining and annual fee of ₹500, the card offers 2 reward points for every ₹100 spent on most categories, and 1 point per ₹100 on utility and insurance payments. Cardholders can enjoy a 25% discount on movie tickets through BookMyShow and INOX, up to ₹100 twice a month. Dining discounts are available under the ICICI Bank Culinary Treats program. The card also provides 1 complimentary domestic airport lounge visit per quarter upon spending ₹75,000 in a quarter, and 4 railway lounge visits per year. An annual fee waiver is available upon spending ₹1.5 lakh in the previous year. While the card offers a range of lifestyle benefits, its reward rate is relatively low, and certain perks require meeting specific spending thresholds.",
    advantages: [
      "Low joining and annual fee of ₹500.",
      "2 reward points per ₹100 on most spends; 1 point per ₹100 on utilities and insurance.",
      "25% discount on movie tickets via BookMyShow and INOX, up to ₹100 twice a month.",
      "Dining discounts under the ICICI Bank Culinary Treats program.",
      "1 complimentary domestic airport lounge visit per quarter on spending ₹75,000 in a quarter.",
      "4 complimentary railway lounge visits per year.",
      "Annual fee waiver on spending ₹1.5 lakh in the previous year.",
    ],
    disadvantages: [
      "Reward rate is relatively low, with a return of 0.25% to 0.75%.",
      "Airport lounge access requires a quarterly spend of ₹75,000.",
      "No international lounge access.",
      "Reward redemption fee of ₹99 + GST.",
      "No rewards on fuel transactions.",
      "Limited premium benefits compared to higher-tier cards.",
    ],
    ratings: {
      reward_points_program: 6.5,
      annual_fee_value: 7.5,
      movie_benefits: 7.0,
      dining_benefits: 7.0,
      lounge_access: 6.0,
      apr_interest_rate: 4.0,
      overall_versatility: 6.5,
    },
  },
  {
    bank: "Axis Bank",
    card_name: "Axis Bank Magnus",
    url: "https://www.axisbank.com/retail/cards/credit-card/axis-bank-magnus-card",
    annual_percentage_rate: "41.75%",
    joining_fee: "₹10,000",
    annual_fee: "₹10,000",
    benefits: [
      "Travel benefits",
      "Complimentary airport lounge access",
      "Luxury experiences",
    ],
    summary:
      "The Axis Bank Magnus Credit Card is a premium offering tailored for high-net-worth individuals seeking luxury travel and lifestyle benefits. With a joining and annual fee of ₹10,000, the card provides a host of privileges, including unlimited international lounge access through Priority Pass (with four guest visits per year) and unlimited domestic lounge access, subject to a quarterly spend of ₹50,000. Cardholders earn 12 EDGE reward points per ₹200 spent up to ₹1.5 lakh monthly, and 35 points per ₹200 on spends beyond that threshold. Purchases via the Travel EDGE portal yield 60 points per ₹200 up to ₹2 lakh monthly. The card also offers a welcome benefit equivalent to the joining fee in the form of Luxe, Yatra, or Postcard Hotels vouchers upon the first transaction. Additional perks include a 1% fuel surcharge waiver on transactions between ₹400 and ₹4,000, purchase protection up to ₹2 lakh, credit shield up to ₹5 lakh, and coverage for loss or delay in baggage and personal documents up to USD 500. The annual fee is waived upon annual spends of ₹25 lakh, excluding categories like fuel, insurance, and gold/jewelry. While the card offers substantial benefits for frequent travelers and high spenders, recent revisions have introduced exclusions in reward categories and discontinued services like concierge assistance and movie ticket offers.",
    advantages: [
      "Unlimited international lounge access via Priority Pass, with four guest visits per year.",
      "Unlimited domestic lounge access, subject to a quarterly spend of ₹50,000.",
      "Accelerated reward points: 12 EDGE points per ₹200 spent up to ₹1.5 lakh monthly; 35 points per ₹200 beyond that.",
      "Enhanced rewards on Travel EDGE portal: 60 points per ₹200 spent up to ₹2 lakh monthly.",
      "Welcome benefit equal to the joining fee in the form of Luxe, Yatra, or Postcard Hotels vouchers.",
      "1% fuel surcharge waiver on transactions between ₹400 and ₹4,000.",
      "Purchase protection up to ₹2 lakh and credit shield up to ₹5 lakh.",
      "Coverage for loss or delay in baggage and personal documents up to USD 500.",
      "No cash withdrawal fees and reduced forex markup fee of 2%.",
    ],
    disadvantages: [
      "High annual fee of ₹10,000, waived only on annual spends of ₹25 lakh, excluding specific categories.",
      "Exclusions in reward points accrual for spends on fuel, insurance, gold, jewelry, utilities, and government payments.",
      "Discontinuation of services like concierge assistance and Buy-One-Get-One movie ticket offers.",
      "Reward redemption options are limited, with reduced transfer ratios for non-Burgundy customers.",
      "Domestic lounge access now requires a minimum quarterly spend of ₹50,000.",
      "No rewards on wallet loads, rent payments, or EMI transactions.",
    ],
    ratings: {
      reward_points_program: 8.5,
      annual_fee_value: 6.5,
      travel_benefits: 9.0,
      lounge_access: 9.0,
      luxury_experiences: 8.0,
      apr_interest_rate: 4.0,
      overall_versatility: 7.0,
    },
  },
  {
    bank: "Citibank",
    card_name: "Citi PremierMiles",
    url: "https://www1.citibank.com.sg/credit-cards/travel/premiermiles-card",
    annual_percentage_rate: "45.0%",
    joining_fee: "₹3,000",
    annual_fee: "₹3,000",
    benefits: [
      "Air mile conversion options",
      "Complimentary air travel",
      "Exclusive discounts on travel bookings",
    ],
    summary:
      "The Citi PremierMiles Credit Card is a travel-focused card designed for frequent flyers seeking flexibility in earning and redeeming air miles. With a joining and annual fee of ₹3,000, cardholders earn 10 miles per ₹100 spent on airline transactions and 4 miles per ₹100 on other spends. The card offers a welcome bonus of 10,000 miles upon spending ₹1,000 within the first 60 days. Miles can be redeemed across 100+ airlines and hotel partners, and they never expire, providing long-term value. Additionally, the card provides complimentary access to select domestic airport lounges. While the card offers robust travel benefits, it lacks certain premium features such as international lounge access and comprehensive travel insurance, making it more suitable for domestic travelers and those seeking flexible redemption options.",
    advantages: [
      "Earn 10 miles per ₹100 on airline transactions and 4 miles per ₹100 on other spends.",
      "Welcome bonus of 10,000 miles on spending ₹1,000 within the first 60 days.",
      "Miles never expire, offering long-term value.",
      "Redeem miles across 100+ airlines and hotel partners.",
      "Complimentary access to select domestic airport lounges.",
      "Lost card liability cover of ₹10 lakh.",
    ],
    disadvantages: [
      "High annual percentage rate (APR) of 45.0%, making it costly for carrying balances.",
      "No international lounge access.",
      "Foreign currency markup fee of 3.5%, which can add up for international travelers.",
      "Lacks comprehensive travel insurance benefits.",
      "Reward redemption options may be limited compared to other premium cards.",
    ],
    ratings: {
      reward_points_program: 7.5,
      annual_fee_value: 7.0,
      lounge_access: 6.0,
      air_mile_conversion: 8.0,
      apr_interest_rate: 4.0,
      overall_versatility: 6.5,
    },
  },
  {
    bank: "Kotak Mahindra Bank",
    card_name: "Kotak Royale Signature",
    url: "https://www.kotak.com/en/personal-banking/cards/credit-cards/royale-signature-credit-card.html",
    annual_percentage_rate: "37.2%",
    joining_fee: "₹999",
    annual_fee: "₹999",
    benefits: [
      "Reward points on all spends",
      "Dining benefits",
      "Fuel surcharge waiver",
    ],
    summary:
      "The Kotak Royale Signature Credit Card is designed for individuals seeking a balance between lifestyle benefits and reward earnings. With a modest annual fee of ₹999, which is waived upon annual spends of ₹1 lakh, the card offers 2 reward points per ₹150 on regular spends and 4 points per ₹150 on special categories such as travel, dining, and international transactions. Cardholders can enjoy up to 8 complimentary domestic airport lounge visits annually, limited to 2 per quarter. Additional perks include a fuel surcharge waiver of up to ₹3,500 per year on transactions between ₹500 and ₹3,000, and a railway surcharge waiver of up to ₹500 annually. The card also provides milestone benefits, offering up to 30,000 bonus reward points on annual retail spends of ₹8 lakhs. While the card offers a range of benefits, it lacks international lounge access and comprehensive travel insurance, making it more suitable for domestic travelers and those seeking lifestyle rewards.",
    advantages: [
      "Earn 2 reward points per ₹150 on regular spends and 4 points per ₹150 on special categories like travel, dining, and international transactions.",
      "Annual fee waiver on spending ₹1 lakh in the previous year.",
      "Up to 8 complimentary domestic airport lounge visits annually (2 per quarter).",
      "Fuel surcharge waiver of up to ₹3,500 per year on transactions between ₹500 and ₹3,000.",
      "Railway surcharge waiver of up to ₹500 annually.",
      "Milestone benefits offering up to 30,000 bonus reward points on annual retail spends of ₹8 lakhs.",
      "Priority Attend service for on-call solutions and complimentary cheque pickup.",
    ],
    disadvantages: [
      "No international lounge access.",
      "Reward points are not earned on fuel and railway surcharge transactions.",
      "Foreign currency markup fee of 3.5%, which can add up for international travelers.",
      "Lacks comprehensive travel insurance benefits.",
      "Reward redemption options may be limited compared to other premium cards.",
    ],
    ratings: {
      reward_points_program: 7.0,
      annual_fee_value: 8.0,
      lounge_access: 6.5,
      fuel_surcharge_waiver: 7.5,
      apr_interest_rate: 5.0,
      overall_versatility: 7.0,
    },
  },
  {
    bank: "American Express",
    card_name: "Amex Platinum Travel",
    url: "https://www.americanexpress.com/in/credit-cards/platinum-travel-credit-card/",
    annual_percentage_rate: "42.0%",
    joining_fee: "₹3,500",
    annual_fee: "₹5,000",
    benefits: [
      "Complimentary travel vouchers",
      "Airport lounge access",
      "Exclusive hotel benefits",
    ],
    summary:
      "The American Express Platinum Travel Credit Card is tailored for frequent domestic travelers who aim to maximize rewards through milestone-based spending. With a joining fee of ₹3,500 and an annual fee of ₹5,000, cardholders earn 1 Membership Rewards (MR) point for every ₹50 spent, excluding categories like fuel, insurance, utilities, and EMI conversions. Achieving annual spends of ₹1.9 lakh and ₹4 lakh unlocks milestone bonuses of 15,000 and 25,000 MR points respectively, redeemable for travel vouchers via the Platinum Travel Collection or Amex Travel Online. Additionally, spending ₹4 lakh annually grants a ₹10,000 Taj Experiences E-Gift Card. The card offers 8 complimentary domestic airport lounge visits per year (limited to 2 per quarter) and complimentary Priority Pass membership, though lounge access via Priority Pass is not included. While the card provides substantial travel benefits, its utility is maximized when the cardholder meets the specified spending thresholds.",
    advantages: [
      "High reward rate of approximately 8.5% on achieving annual spend milestones.",
      "Welcome bonus of 10,000 MR points upon spending ₹15,000 within the first 90 days.",
      "8 complimentary domestic airport lounge visits per year (2 per quarter).",
      "Complimentary Priority Pass membership with the US$99 annual fee waived.",
      "₹10,000 Taj Experiences E-Gift Card on annual spends of ₹4 lakh.",
      "MR points do not expire as long as the card is active and in good standing.",
      "Up to 20% discount at select partner restaurants.",
    ],
    disadvantages: [
      "Benefits are heavily reliant on achieving specific annual spend milestones.",
      "No complimentary international lounge access despite Priority Pass membership.",
      "Limited acceptance of American Express cards in certain establishments across India.",
      "High annual percentage rate (APR) of 42.0%, making it costly for carrying balances.",
      "Foreign currency markup fee of 3.5%, which can add up for international travelers.",
      "Reward points are not earned on fuel, insurance, utilities, cash transactions, and EMI conversions.",
    ],
    ratings: {
      reward_points_program: 8.5,
      annual_fee_value: 7.0,
      lounge_access: 7.0,
      travel_benefits: 8.0,
      apr_interest_rate: 4.0,
      overall_versatility: 6.5,
    },
  },
  {
    bank: "Standard Chartered",
    card_name: "SC Manhattan",
    url: "https://www.sc.com/in/credit-cards/",
    annual_percentage_rate: "45.0%",
    joining_fee: "₹999",
    annual_fee: "₹999",
    benefits: [
      "5% cashback on supermarkets",
      "Reward points on all other spends",
      "Dining discounts",
    ],
    summary:
      "The Standard Chartered Manhattan Platinum Credit Card is tailored for individuals who frequently shop at supermarkets and departmental stores. Cardholders earn 5% cashback on such purchases, subject to a maximum of ₹150 per transaction and ₹500 per month. For all other spends, the card offers 3 reward points per ₹150 spent. A welcome benefit of 5,000 reward points is provided upon payment of the joining fee. The annual fee of ₹999 is waived upon annual spends of ₹1.2 lakh. While the card offers valuable cashback and rewards for everyday shopping, it lacks premium features such as airport lounge access and comprehensive travel benefits.",
    advantages: [
      "5% cashback on supermarket and departmental store purchases, up to ₹500 per month.",
      "3 reward points per ₹150 spent on all other categories.",
      "Welcome bonus of 5,000 reward points upon payment of joining fee.",
      "Annual fee waiver on spending ₹1.2 lakh in the previous year.",
      "Access to exclusive offers and discounts through the Standard Chartered Good Life programme.",
    ],
    disadvantages: [
      "Cashback is capped at ₹150 per transaction and ₹500 per month.",
      "No airport lounge access.",
      "High annual percentage rate (APR) of 45.0%, making it costly for carrying balances.",
      "Foreign currency markup fee of 3.5%, which can add up for international travelers.",
      "Lacks comprehensive travel insurance benefits.",
    ],
    ratings: {
      reward_points_program: 6.5,
      annual_fee_value: 7.0,
      cashback_benefits: 7.5,
      dining_benefits: 6.0,
      apr_interest_rate: 4.0,
      overall_versatility: 6.5,
    },
  },
  {
    bank: "HSBC",
    card_name: "HSBC Visa Platinum",
    url: "https://www.hsbc.co.in/credit-cards/products/visa-platinum/",
    annual_percentage_rate: "45.0%",
    joining_fee: "₹0",
    annual_fee: "₹0",
    benefits: [
      "Earn 2 Reward points for every ₹150 spent",
      "5X Reward points on spends over ₹4 lakh annually, capped at 15,000 points per year",
      "Air miles conversion with leading airlines",
      "Fuel surcharge waiver up to ₹3,000 per year",
      "Welcome benefits including ₹250 Amazon voucher and ₹500 cashback on spending ₹5,000 within the first 30 days",
      "3 complimentary domestic/international airport lounge visits",
      "Zero liability on lost card if reported within 24 hours",
      "Emergency card replacement within 3 days",
    ],
    summary:
      "The HSBC Visa Platinum Credit Card is a lifetime free credit card offering a range of benefits tailored for individuals seeking rewards on everyday spending. With no joining or annual fees, cardholders earn 2 Reward points for every ₹150 spent. Additionally, spending over ₹4 lakh annually unlocks 5X Reward points, capped at 15,000 points per year. The card also provides air miles conversion with leading airlines, a fuel surcharge waiver up to ₹3,000 per year, and welcome benefits including a ₹250 Amazon voucher and ₹500 cashback on spending ₹5,000 within the first 30 days. Other perks include 3 complimentary domestic/international airport lounge visits, zero liability on lost card if reported within 24 hours, and emergency card replacement within 3 days.",
    advantages: [
      "No joining or annual fees, making it a lifetime free credit card",
      "Earn 2 Reward points for every ₹150 spent, with 5X points on spends over ₹4 lakh annually",
      "Air miles conversion with leading airlines",
      "Fuel surcharge waiver up to ₹3,000 per year",
      "Welcome benefits including ₹250 Amazon voucher and ₹500 cashback on spending ₹5,000 within the first 30 days",
      "3 complimentary domestic/international airport lounge visits",
      "Zero liability on lost card if reported within 24 hours",
      "Emergency card replacement within 3 days",
    ],
    disadvantages: [
      "5X Reward points are capped at 15,000 points per year, requiring significant annual spending to maximize benefits",
      "No international lounge access",
      "High annual percentage rate (APR) of 45.0%, making it costly for carrying balances",
      "Foreign currency markup fee of 3.5%, which can add up for international travelers",
      "Lacks comprehensive travel insurance benefits",
    ],
    ratings: {
      reward_points_program: 7.5,
      annual_fee_value: 9.0,
      lounge_access: 6.0,
      air_mile_conversion: 7.0,
      fuel_surcharge_waiver: 7.5,
      welcome_benefits: 8.0,
      overall_versatility: 7.5,
    },
  },
  {
    bank: "RBL Bank",
    card_name: "RBL Bank ShopRite",
    url: "https://www.rblbank.com/personal-banking/cards/credit-cards/shoprite-credit-card",
    annual_percentage_rate: "42.0%",
    joining_fee: "₹500",
    annual_fee: "₹500",
    benefits: [
      "Reward points on grocery and departmental store spends",
      "Fuel surcharge waiver",
    ],
    summary:
      "The RBL Bank ShopRite Credit Card is a budget-friendly option tailored for individuals who frequently shop for groceries and enjoy occasional entertainment perks. With a nominal annual fee of ₹500, which can be waived upon spending ₹1.5 lakh in a membership year, this card offers a variety of rewards and discounts. Cardholders can earn 20 reward points for every ₹100 spent on grocery purchases, capped at 1,000 points per month, translating to a 5% value back on such expenses. Other purchases earn 1 reward point per ₹100 spent. Additional benefits include a 10% discount (up to ₹100) on movie tickets at BookMyShow, valid for up to 15 bookings per year, and a fuel surcharge waiver of up to ₹100 per month on fuel transactions between ₹500 and ₹4,000. The card also offers a welcome benefit of 2,000 reward points upon meeting certain conditions.",
    advantages: [
      "Earn 20 reward points for every ₹100 spent on grocery purchases, offering a 5% value back",
      "Receive a 10% discount (up to ₹100) on movie tickets at BookMyShow, applicable 15 times a year",
      "Get a waiver of up to ₹100 per month on fuel transactions between ₹500 and ₹4,000",
      "Earn 2,000 reward points as a welcome benefit on valid retail transaction and annual fee payment",
      "Annual fee waiver on spending ₹1.5 lakh or more in the previous membership year",
    ],
    disadvantages: [
      "Grocery rewards are capped at 1,000 points per month, limiting the maximum value back to ₹250 monthly",
      "High annual percentage rate (APR) of 42.0%, costly if balances are carried forward",
      "No complimentary airport lounge access",
      "Reward redemption fee of ₹99 plus GST applicable per redemption",
      "Certain categories like utilities, insurance premiums, and EMI transactions are excluded from reward points",
    ],
    ratings: {
      grocery_rewards: 8,
      movie_discounts: 7,
      fuel_surcharge_waiver: 6,
      welcome_benefit: 7,
      annual_fee_waiver: 6,
      overall_value: 7,
    },
  },
];
